author : Adelowo Lanre
title : Adelowo Lanre • Web Developer From Lagos - Nigeria
email: me@adelowolanre.com

baseurl: ""
url: "http://adelowolanre.com"
permalink: /blog/:year/:month/:day/:title/

social :
  twitter : adelowolanre
  github : adelowo
  stackoverflow : 4301733/adelowo
  quora : Adelowo-Lanre-1
  facebook : adelowo.lanre.5
  linkedin : adelowolanre



# Build settings
markdown: kramdown

disqus:
  shortname : adelowo

sass:
  style: :compressed

googleanalytics: UA-71600006-1

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
