plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

exclude: ['package.json', 'src', 'node_modules', 'Gemfile', 'Gemfile.lock','LICENSE','CNAME', 'README.md', 'yarn.lock', 'gulpfile.js']

# Site settings
title: Lanre Adelowo - Software Developer interested in the web
description: "A blog on Software Development"
url: "https://lanre.wtf"
# User settings
username: adelowo
user_title: Lanre Adelowo
email: yo@lanre.wtf
twitter_username: lanreadelowo
github_username:  adelowo
disqus_username: adelowo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

