author: Lanre Adelowo
title : Lanre Adelowo • Web Developer From Lagos - Nigeria
email : me@lanreadelowo.com

url: http://lanreadelowo.com
permalink: /blog/:year/:month/:day/:title/

social :
  twitter : adelowolanre
  github : adelowo
  stackoverflow : 4301733/adelowo
  quora : Lanre-Adelowo
  facebook : adelowo.lanre.5
  linkedin : adelowolanre



# Build settings
markdown: kramdown

disqus:
  shortname : adelowo

sass:
  style: :compressed

googleanalytics: UA-71600006-1

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
