gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

exclude: ['package.json', 'src', 'node_modules', 'Gemfile', 'Gemfile.lock','LICENSE','CNAME', 'README.md']

# Site settings
title: Lanre-Adelowo - Web Developer
description: "A blog on Software Development"
url: "http://lanreadelowo.com" 
# User settings
username: adelowo
user_title: Lanre Adelowo
email: me@lanreadelowo.com
twitter_username: lanreadelowo
github_username:  adelowo
disqus_username: adelowo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /blog
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: gbowo
    url: https://github.com/adelowo/gbowo
