gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

exclude: ['package.json', 'src', 'node_modules', 'Gemfile', 'Gemfile.lock','LICENSE','CNAME', 'README.md', 'yarn.lock', 'gulpfile.js']

# Site settings
title: Lanre-Adelowo - Software Developer interested in the web
description: "A blog on Software Development"
url: "https://lanreadelowo.com" 
# User settings
username: adelowo
user_title: Lanre Adelowo
email: me@lanreadelowo.com
twitter_username: lanreadelowo
github_username:  adelowo
disqus_username: adelowo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /blog
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: Onecache
    url: https://github.com/adelowo/onecache/
    description: A caching library for Golang with support for redis, filesystem, memcached and an inmemory backend

  - name: Gbowo
    url: https://github.com/adelowo/gbowo
    description: A payment library for Paystack and Amplifypay

  - name: Fileupload
    url: https://github.com/Gargron/fileupload
    description: "A Document upload library that supports chunked uploads. I help maintain this project"  

  - name: Gbowo-paystack
    url:  https://github.com/adelowo/gbowo-paystack
    description: This is a companion library to Gbowo. And it contains plugins for Gbowo's Paystack adapter.
