author : Adelowo Lanre
title : Adelowo Lanre • Web Developer From Lagos, Nigeria
email: me@domain.com

baseurl: ""
url: "http://adelowolanre.com"
permalink: /blog/:year/:month/:day/:title/

social :
  twitter : adelowolanre
  github : adelowo
  stackoverflow : 4301733/adelowo
  quora : Adelowo-Lanre-1
  facebook :
  linkedin :



# Build settings
markdown: kramdown

disqus:
  shortname :

sass:
  style: :compressed

googleanalytics:

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME