baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "lanreadelowo"
pygmentsUseClasses=true
disqusShortname = "adelowo"

[permalinks]
  blog = "/:year/:month/:day/:slug/"

[params]
  name = "Lanre Adelowo"
  email = "yo@lanre.wtf"
  homepage = "https://lanre.wtf"
  twitter = "https://twitter.com/lanreadelowo"
  github = "https://github.com/adelowo"
