baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "lanreadelowo"
pygmentsUseClasses=true
disqusShortname = "adelowo"

[params]
  name = "Lanre Adelowo"
  email = "yo@lanre.wtf"
  homepage = "https://lanre.wtf"
